config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :groups do
    resources :spaces, :locations
  end

  resources :spaces

  root 'welcome#index'
end

app/models/group.rb
require 'open-uri'

class Group < ActiveRecord::Base
  has_many :spaces, dependent: :destroy
  has_many :location, dependent: :destroy
  validates :title, presence: true

  def avaliable_spaces
    url =JSON.load(open('http://parker2.api.streetlinenetworks.com/api/testing/availability/f3/la/availability.json?decode=true'))
    availability= url["availability"]["availabilityBitsDecoded"]

    spaces = Space.where(group_id: self.id)
    open =  0
    spaces.each{|space| 
      space_id = space["unique_id"] - 1
      if availability[space_id] == '1'
        open += 1 
      end
    }
    return open
  end

  def spaces 
    return spaces = Space.where(group_id: self.id)
  end


end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :group
end

app/models/space.rb
class Space < ActiveRecord::Base
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "password", except: [:index, :show]
  
  def index
    @groups = Group.where(kind: 'block').order("id").page(params[:page])
    # @locations = @groups.all.each do |group| group["location"] end
    @hash = Gmaps4rails.build_markers(@groups.map(&:location)) do |location, marker|
      marker.lat location[0]['latitude']
      marker.lng location[0]['longitude']
      group = Group.find(location[0]['group_id'])
      marker.infowindow("#{group['title']}: #{group.avaliable_spaces}/#{group.spaces.size} spaces are avaliable spaces")
    end
  end  

  def show
    @group = Group.find(params[:id])
    @spaces = Space.where(group_id: @group.id)
  end

  def new
    @group = Group.new
  end
  
  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)
   
    if @group.save
        redirect_to @group
    else
        render 'new'
    end
  end

  def update
    @group = Group.find(params[:id])
   
    if @group.update(group_params)
      redirect_to @group
    else
      render 'edit'
    end
end

def destroy
  @group = Group.find(params[:id])
  @group.destroy
  redirect_to groups_path
end 
   
private
  def group_params
    params.require(:group).permit(:title, :kind)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def create
    @group = Group.find(params[:group_id])
    @location = @group.locations.create(location_params)
    redirect_to group_path(@group)
  end

  private
    def location_params
      params.require(:location).permit(:latitude)
    end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "password"

  def create
    @group = Group.find(params[:group_id])
    @space = @group.spaces.create(space_params)
    redirect_to group_path(@group)
  end

  def destroy
    @group = Group.find(params[:group_id])
    @space = @group.spaces.find(params[:id])
    @space.destroy
    redirect_to group_path(@group)
  end
 
  private
    def space_params
      params.require(:space).permit(:policy)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
 
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@group.errors.count, "error") %> prohibited
        this group from being saved:
      </h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :kind %><br>
    <%= f.text_area :kind %>
  </p>

  <%= fields_for :location do |location_fields| %>
    <p>
      <%= location_fields.label :latitude %><br>
      <%= location_fields.text_field :latitude %>
    </p>
     <p>
      <%= location_fields.label :latitude_delta %><br>
      <%= location_fields.text_field :latitude_delta %>
    </p>
    <p>
      <%= location_fields.label :longitude %><br>
      <%= location_fields.text_field :longitude %>
    </p>
    <p>
      <%= location_fields.label :longitude_delta %><br>
      <%= location_fields.text_field :longitude_delta %>
    </p>
  <% end %>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>
 
<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>
<td><%= link_to 'New group', new_group_path %></td>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<%= paginate  @groups %>
<table>
  <tr>
    <th>Title</th>
    <th>Kind</th>
    <th colspan="2"></th>
  </tr>
 
  <% @groups.each do |group| %>
    <tr>
      <td><%= link_to group.title, group_path(group) %></td>
      <td><%= group.kind %></td>
      <td><%= link_to 'Show', group_path(group) %></td>
      <td><%= link_to 'Edit', edit_group_path(group) %></td>
      <td><%= link_to 'Destroy', group_path(group),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @group.title %>
</p>
 
<p>
  <strong>Kind:</strong>
  <%= @group.kind %>
</p>

<p>
  <strong>Location:</strong>
  <%= @group.location %>
</p>

<h2>Spaces AHSDHFA</h2>
<%= @spaces.each do |space| %>
  <p>Stuff</p>
<% end %>

<h2>Spaces</h2>
<%= render 'spaces/index', :group => @group.id %>

<h2>Add a space:</h2>
<%= render 'spaces/form' %>

<%= link_to 'Edit', edit_group_path(@group) %> |

<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Streetline</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spaces/_form.html.erb
<%= form_for([@group, @group.spaces.build]) do |f| %>
  <p>
    <%= f.label :policy %><br>
    <%= f.text_field :policy %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/spaces/_index.html.erb
<%= Space.where(:group_id => group).each do |space|%>
  <p>
    <strong>ID:</strong>
    <%= space.unique_id %>
    <strong> Group ID: </strong>
    <%= space.group_id %>
   <%= link_to 'Destroy space', [space.group, space],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

app/views/spaces/_space.html.erb
<% @group.spaces.where(group_id: @group.id).each do |space| %>
  <p>
    <strong>ID:</strong>
    <%= space.unique_id %>
    <strong> Group ID: </strong>
    <%= space.group_id %>
   <%= link_to 'Destroy Space', [space.group, space],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Zo's APP</h1>
<%= link_to 'All Space Groups', controller: 'groups' %>